"""Deterministic public synthetic L2 book-update fixtures; no market data."""
import argparse
from pathlib import Path

MASK = (1 << 64) - 1


class SplitMix64:
    def __init__(self, seed: int):
        self.state = seed & MASK

    def next(self) -> int:
        self.state = (self.state + 0x9E3779B97F4A7C15) & MASK
        z = self.state
        z = ((z ^ (z >> 30)) * 0xBF58476D1CE4E5B9) & MASK
        z = ((z ^ (z >> 27)) * 0x94D049BB133111EB) & MASK
        return z ^ (z >> 31)


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("output", type=Path)
    p.add_argument("--feeds", type=int, default=4)
    p.add_argument("--events", type=int, default=200)
    p.add_argument("--seed", type=int, default=1701)
    p.add_argument("--pattern", choices=["uniform", "ties", "bursty", "sessions"], default="uniform")
    p.add_argument("--levels", type=int, default=8, help="distinct price levels per side")
    a = p.parse_args()
    if not 0 <= a.feeds <= 4096 or a.events < 0 or a.levels < 1:
        p.error("invalid fixture size")
    rng = SplitMix64(a.seed)
    with a.output.open("w") as out:
        out.write("# available_ns feed_id session seq venue_ns side price_ticks qty\n")
        out.write(f"# generated by tools/generate_book.py --feeds {a.feeds} --events {a.events} --seed {a.seed} --pattern {a.pattern} --levels {a.levels}\n")
        for f in range(a.feeds):
            t = 0
            session = 0
            seq = 0
            n = a.events
            for i in range(n):
                delta = rng.next() % (1 if a.pattern == "ties" else 11)
                if a.pattern == "bursty":
                    delta = 0 if i % 64 else 1000
                t += delta
                if a.pattern == "sessions" and i > 0 and i % 50 == 0:
                    session += 1
                    seq = 0
                if rng.next() % 23 == 0:
                    side, price, qty = "R", 0, 0
                else:
                    side = "B" if rng.next() % 2 == 0 else "A"
                    price = 10_000 + rng.next() % a.levels
                    qty = 0 if rng.next() % 7 == 0 else 1 + rng.next() % 500
                out.write(f"{t}\t{f}\t{session}\t{seq}\t{t - 100}\t{side}\t{price}\t{qty}\n")
                seq += 1


if __name__ == "__main__":
    main()
